function g = mets_payoff_advantages(u,p)
% Active-minus-passive expected payoffs, in [government company platform MRV].
x=u(1); y=u(2); z=u(3); r=u(4);
g = [(1-y)*p.F1+(1-r)*p.F3-y*p.P1-z*p.P2-r*p.P3-p.DeltaC1+p.S; ...
     x*(p.P1+p.F1)-p.DeltaC2+p.L+p.K+p.E; ...
     x*p.P2-p.DeltaC3+p.D; ...
     x*(p.P3+p.F3)-p.DeltaC4+p.V];
end
